### ISSUE TITLE
cannot build with ghc-8.0.2 (rc2) because of version bound for directory

### ISSUE THREAD

**Issue by jwaldmann** [haskell/ThreadScope#59]
When I do `cabal install threadscope` with ghc 8.0.1.20161213 (= 8.0.2-rc2), I get

```
Resolving dependencies...
internal error: could not construct a valid install plan.
The proposed (invalid) plan contained the following problems:
Package directory is required by several packages, but they require
inconsistent versions:
package gtk2hs-buildtools-0.13.2.1 requires directory-1.2.7.1
package Cabal-1.24.2.0 requires directory-1.2.7.1
package process-1.4.3.0 requires directory-1.3.0.0
```

adding `--allow-newer`, a build plan is found, and compilation happily starts.

**Comment by Mikolaj** [comment]
Thank you for the report and for the --allow-newer trick. I've already reported the gtk2hs issue here: https://github.com/gtk2hs/gtk2hs/issues/193

Since TS does not depend directly on directory, nor sets an upper bound on it, nor on gtk2hs, we can close this issue, unless we want the --allow-newer trick to be visible to any future reporters.

**Comment by kvelicka** [comment]
https://github.com/gtk2hs/gtk2hs/pull/197 is merged so I assume this is no longer an issue.
